name: Add resource
description: 推荐一个值得收录的 AI 工程资源/项目
title: "[Add] owner/repo"
labels: ["add-resource"]
body:
  - type: input
    id: repo
    attributes:
      label: 仓库链接
      description: GitHub 仓库链接（必填）
      placeholder: https://github.com/owner/repo
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: 建议分类
      options:
        - agents/workflows（LLM应用框架/编排）
        - RAG/检索/向量数据库
        - evals/testing（评测与回归）
        - 可观测/调试/streaming
        - 推理/部署/runtime
        - 安全/合规/脱敏
        - 文档/数据处理（parsing/ETL）
        - 开发者工具（CLI/插件/模板）
    validations:
      required: true

  - type: textarea
    id: value
    attributes:
      label: 一句话价值（建议）
      description: 用 1 句话描述它解决什么问题（不要营销语）
      placeholder: 例如：为 RAG 提供可复现的评测与回归基线……
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: 适用场景
      description: 给出 1–3 个具体场景（越具体越好）
      placeholder: |
        - 场景 1：
        - 场景 2：
    validations:
      required: true

  - type: textarea
    id: caveats
    attributes:
      label: 注意事项 / 不适用
      description: 至少 1 条（非常重要）
      placeholder: |
        - 注意事项 1：
        - 注意事项 2（可选）：
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: 引用/参考链接
      description: 至少 1 条（优先 README/Docs）。不确定请写 TODO，不要编造。
      placeholder: |
        - README/Docs：
        - 其他（可选）：
    validations:
      required: true

